// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD93059iooSnq83fGipqLgXef3N-k7JX2Q',
    appId: '1:1015852794537:web:0ded9df8d775fdcdd25fb8',
    messagingSenderId: '1015852794537',
    projectId: 'offlinegamesinvisiblemaze',
    authDomain: 'offlinegamesinvisiblemaze.firebaseapp.com',
    storageBucket: 'offlinegamesinvisiblemaze.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8uTOyfS3p6r65fVd12iuDqtf0311E2_M',
    appId: '1:1015852794537:android:7162614c0117b6a3d25fb8',
    messagingSenderId: '1015852794537',
    projectId: 'offlinegamesinvisiblemaze',
    storageBucket: 'offlinegamesinvisiblemaze.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKbqdC5s7pq2cYR43JnHQXpXqfBUnmTM0',
    appId: '1:1015852794537:ios:3eaacfb01f445cfcd25fb8',
    messagingSenderId: '1015852794537',
    projectId: 'offlinegamesinvisiblemaze',
    storageBucket: 'offlinegamesinvisiblemaze.firebasestorage.app',
    iosBundleId: 'com.cypher.invisiblemaze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKbqdC5s7pq2cYR43JnHQXpXqfBUnmTM0',
    appId: '1:1015852794537:ios:934229677ba736c3d25fb8',
    messagingSenderId: '1015852794537',
    projectId: 'offlinegamesinvisiblemaze',
    storageBucket: 'offlinegamesinvisiblemaze.firebasestorage.app',
    iosBundleId: 'com.example.invisiblemaze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD93059iooSnq83fGipqLgXef3N-k7JX2Q',
    appId: '1:1015852794537:web:6f50d4e5027cc424d25fb8',
    messagingSenderId: '1015852794537',
    projectId: 'offlinegamesinvisiblemaze',
    authDomain: 'offlinegamesinvisiblemaze.firebaseapp.com',
    storageBucket: 'offlinegamesinvisiblemaze.firebasestorage.app',
  );

}